name 'winapp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures winapp'
long_description 'Installs/Configures winapp'
version '0.1.36'

depends 'sql_server', '~> 2.5.0'
depends 'iis', '~> 4.1.6'
